// <auto-generated />
namespace UCDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class inicializando_classe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicializando_classe));
        
        string IMigrationMetadata.Id
        {
            get { return "202008280001437_inicializando_classe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
